// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
import java.util.EnumMap;
import java.util.Map;

public class Bank {
	//bank has infinite resources, but we track it
	private Map<Resource, Integer> counts;

	public Bank() {
		counts = new EnumMap<>(Resource.class);
		for (Resource r : Resource.values()) {
			counts.put(r, 19); //standard limit tho
		}
	}

	public boolean canGive(Resource r, int n) {
		return counts.getOrDefault(r, 0) >= n;
	}

	public void give(Player p, Resource r, int n) {
		if (r == null) return; // Desert
		p.addResource(r, n);
	}
}
