// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
public class DicePair implements Dice {
	private RegularDice die1 = new RegularDice();
	private RegularDice die2 = new RegularDice();

	@Override
	public int roll() {
		return die1.roll() + die2.roll();
	}
}
