// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
import java.util.EnumMap;
import java.util.Map;
import java.util.Random;

public class Player {
	private int id;
	private Map<Resource, Integer> hand = new EnumMap<>(Resource.class);
	private int roadsLeft = 15;
	private int settlementsLeft = 5;
	private int citiesLeft = 4;
	private int victoryPoints = 0;
	private Random rand = new Random();

	public Player(int id) {
		this.id = id;
		for (Resource r : Resource.values()) hand.put(r, 0);
	}

	public int id() { return id; }
	public int vp() { return victoryPoints; }

	public void addResource(Resource r, int num) {
		hand.put(r, hand.get(r) + num);
	}

	public boolean hasResources(Map<Resource, Integer> cost) {
		for (Map.Entry<Resource, Integer> entry : cost.entrySet()) {
			if (hand.get(entry.getKey()) < entry.getValue()) return false;
		}
		return true;
	}

	//pay for the resource
	public void pay(Map<Resource, Integer> cost) {
		for (Map.Entry<Resource, Integer> entry : cost.entrySet()) {
			hand.put(entry.getKey(), hand.get(entry.getKey()) - entry.getValue());
		}
	}

	//taking turn for each player
	public void takeTurn(Game game) {

		//logic for attempting to build if the amount of cards exceeds 7
		//completed > 7 logic*****
		boolean mustBuild = totalCards() > 7;
		//we also implement a 30% random chance that they do nothing in the case they have under 7 cards (to introduce more noise in the samples)
		if (!mustBuild && rand.nextDouble() < 0.30) {
			return;
		}
		//now attempt to build city
		Map<Resource, Integer> cityCost = Map.of(Resource.ORE, 3, Resource.WHEAT, 2);
		if (hasResources(cityCost) && citiesLeft > 0) {
			//find a node to upgrade to a city
			for (Node n : game.board().getNodes()) {
				if (game.upgradeToCity(this, n.getId())) return;
			}
		}

		//try to build a settlement
		Map<Resource, Integer> setCost = Map.of(Resource.BRICK, 1, Resource.WOOD, 1, Resource.WHEAT, 1, Resource.SHEEP, 1);
		if (hasResources(setCost) && settlementsLeft > 0) {
			//then find a valid node
			for (int i=0; i<54; i++) {
				if (game.buildSettlement(this, i)) return;
			}
		}

		//and then finally we try to build a road
		Map<Resource, Integer> roadCost = Map.of(Resource.BRICK, 1, Resource.WOOD, 1);
		if (hasResources(roadCost) && roadsLeft > 0) {
			for (Edge e : game.board().getEdges()) {
				if (game.buildRoad(this, e.getId())) return;
			}
		}
	}

	//helper for total cards of this player
	public int totalCards() {
		return hand.values().stream().mapToInt(Integer::intValue).sum();
	}
	public void addVictoryPoints(int n) { victoryPoints += n; }


	public int getRoadsLeft() {
		return roadsLeft;
	}

	public int getSettlementsLeft() {
		return settlementsLeft;
	}

	public int getCitiesLeft() {
		return citiesLeft;
	}

	public void setRoadsLeft(int roadsLeft) {
		this.roadsLeft = roadsLeft;
	}

	public void setSettlementsLeft(int settlementsLeft) {
		this.settlementsLeft = settlementsLeft;
	}

	public void setCitiesLeft(int citiesLeft) {
		this.citiesLeft = citiesLeft;
	}


}
