// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
public class Tile {
	private int id;
	private Terrain terrain;
	private int number; //dice number frmo 2 to 12

	public Tile(int id, Terrain terrain, int number) {
		this.id = id;
		this.terrain = terrain;
		this.number = number;
	}

	//convert terrain to resource
	public Resource getResource() {
		switch(terrain) {
			case FOREST: return Resource.WOOD;
			case HILLS: return Resource.BRICK;
			case FIELDS: return Resource.WHEAT;
			case PASTURE: return Resource.SHEEP;
			case MOUNTAINS: return Resource.ORE;
			default: return null;
		}
	}

	public int getId() {
		return id;
	}

	public Terrain getTerrain() {
		return terrain;
	}

	public int getNumber() {
		return number;
	}
}
