// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
public class Edge {
	private int id;
	private int endpoint1; // Node ID
	private int endpoint2; // Node ID
	private int roadOwner = -1; // -1 means empty

	public Edge(int id, int endpoint1, int endpoint2) {
		this.id = id;
		this.endpoint1 = endpoint1;
		this.endpoint2 = endpoint2;
	}

	public boolean empty() {
		return roadOwner == -1;
	}

	public int getId() {
		return id;
	}

	public int getEndpoint1() {
		return endpoint1;
	}

	public int getEndpoint2() {
		return endpoint2;
	}

	public int getRoadOwner() {
		return roadOwner;
	}
	public void setRoadOwner(int roadOwner) {
		this.roadOwner = roadOwner;
	}
}
